---
title: "Contributing"
author: "Andrew Marx"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Contributing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction

The package was designed so that users can contribute their own datasets to the package via GitHub. Given that this isn't designed like a typical data package for R, the process of adding datasets is a little more complicated. This article outlines the requirements and process needed to make contributions that take advantage of the features the package offers to users.


# Background

This package is a little unusual in that it can create datasets from user-contributed functions. These functions can create datasets based on zero, one, or more data files. Because of this behavior, this page attempts to distinguish a *"data file"* and a *"dataset"* as two different things. A *data file* is, as the name implies, a file containing data. It gets imported into the package and documented like a normal data package. A *dataset* might contain


# Setup

In order to contribute directly, you will need up-to-date versions of the `devtools`, `usethis`, and `testthat` packages in R.

Contributions should be submitted by forking the *contribute* branch of the package on GitHub. Once you've implemented and tested your additions, submit a pull request.


# Data Files

Any type of ecological data is welcome in the package, whether it's real world data or artificially generated. Additionally, having multiple sources of data that otherwise serve the same educational purposes is welcome; variety gives educators more choices when it comes to developing educational material. While small/relatively simple data files are welcome, consideration should be given to how the dynamic dataset capabilities of the package can be leveraged. For example, a data file with two columns (let's say *mass* and *age*) might be suitable for something like linear regression, but by adding additional columns (e.g., *sex*, *location*, etc), the data file becomes useful for additional things, like GLMs. Likewise, having a large number of rows can be advantageous to the package; data sets can be designed to do things like break a large data file into multiple smaller datasets. So when submitting a real world data file, don't feel the need to trim it down to fit a singular purpose, and when generating artificial data files, consider if adding additional variables or observations might make them useful in new ways.

Multiple related data files are also welcome in the package. When adding them, they should just be treated individually as separate data files, but with information in the descriptions explaining the relationships. Then, if desired, dynamic datasets can be created that combine files however it makes sense.


### Adding Files

To add a data file, it should be added to the `./data-raw/data/` folder. Names must start with a lowercase letter (a-z), but otherwise can contain lowercase letters, numbers, and underscores (_).

Currently, the package is only set up to include csv files. By default, the package does not import "NA" strings in csv files as `NA`. Therefore, csv files should leave fields blank for `NA` values. The package also does not import strings as factors.

Additionally, the package skips the first five lines of csv during import. These lines are assumed to contain metadata about the file. At the very least, it should contain a description, info about the source of the data (such as a URL to a data repository), and a license (Preferably CC0). If relevant, citation information should also be included.


### Documentation Files

All raw data files must be documented with Roxygen. This is accomplished by updating the `./R/data.R` file. Entries in this file should be in alphabetical order by name, and should include an overall description of the data, the source, and a description of the individual fields. The `"lepanthes_rupestris"` entry serves as an example of how to prepare the new entry.


# Datasets

The package automatically generates a base dataset for each data file 


# Categorization


# Building

Once all the files have been prepared, they must be "built" to be included into the package. First, the './data-raw/build-data.R' script should be run in its entirety. This takes all the raw information and builds the *.rda* files that will be included with the package.

If the documentation in `./R/data.R` was updated, then `devtools::document()` should be run to rebuild the package documentation. It will produce a warning about the NAMESPACE file that can be ignored.


# Validating

The first step to validate the new additions is to run `devtools::test()`. It will warn if there were any spelling inconsistencies or unused values in the categorization tables.

The next step is to run `devtools::check()`, which will check that the changes meet CRAN requirements. There should be no errors, warnings, or notes.
